language: python

branches:
  only:
    - master

env:
  COLLECTION_PATH=ansible_collections/mattclay/vmware_demo_collection

services:
  - docker

install:
  - pip install git+https://github.com/ansible/ansible.git@ef94e3c72a9afb96ba06a66edc0371e35fb3be56 --disable-pip-version-check

script:
  - pwd
  - env
  - mkdir $TRAVIS_TMPDIR/$COLLECTION_PATH
  - cd $TRAVIS_TMPDIR/$COLLECTION_PATH
  - cp -av $TRAVIS_BUILD_DIR .
