language: python

python:
  - "3.6"

branches:
  only:
    - master

services:
  - docker

env:
  COLLECTION_PATH=ansible_collections/mattclay/vmware_demo_collection
  TEST_OPTIONS=--docker --color -v --truncate 0

install:
  - pip install ansible==2.9.0rc1 --disable-pip-version-check
  - mkdir -p "$TRAVIS_TMPDIR/$COLLECTION_PATH"
  - cp -aT "$TRAVIS_BUILD_DIR" "$TRAVIS_TMPDIR/$COLLECTION_PATH"
  - cd "$TRAVIS_TMPDIR/$COLLECTION_PATH"

script:
  - ansible-test sanity $TEST_OPTIONS
  - ansible-test units $TEST_OPTIONS
  - ansible-test integration $TEST_OPTIONS --retry-on-error --python 2.7
  - ansible-test integration $TEST_OPTIONS --retry-on-error --python 3.7
