language: python

python:
  - "3.6"

branches:
  only:
    - master

env:
  COLLECTION_PATH=ansible_collections/mattclay/vmware_demo_collection

services:
  - docker

install:
  - pip install ansible==2.9.0rc1 --disable-pip-version-check
  - mkdir -p "$TRAVIS_TMPDIR/$COLLECTION_PATH"
  - cp -aT "$TRAVIS_BUILD_DIR" "$TRAVIS_TMPDIR/$COLLECTION_PATH"
  - cd "$TRAVIS_TMPDIR/$COLLECTION_PATH"

script:
  - ansible-test sanity --docker -v --color --truncate 0
  - ansible-test units --docker -v --color --truncate 0
  - ansible-test integration --docker -v --color --retry-on-error --python 2.7 --truncate 0
  - ansible-test integration --docker -v --color --retry-on-error --python 3.7 --truncate 0
