name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        path: ~/.ansible/collections/ansible_collections/mattclay/vmware_demo_collection
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Ansible
      run: pip install git+https://github.com/ansible/ansible.git@6c78f02121b1742e63d2b2d66a98a4c760f706ad
    - name: Run sanity tests
      run: ansible-test sanity --venv -v --color
    - name: Run unit tests
      run: ansible-test units --venv -v --color
