name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      path: ~/.ansible/collections/ansible_collections/mattclay/vmware_demo_collection
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Ansible
      run: pip install ansible --pre
    - name: Run sanity tests
      run: ansible-test sanity --venv -v
