name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/mattclay/vmware_demo_collection
      - name: Install Ansible
        run: pip install ansible-base==2.10.0 --disable-pip-version-check
      - name: Install Collection Requirements
        run: ansible-galaxy collection install -r requirements.yml -p ../../../
      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
      - name: Run unit tests
        run: ansible-test units --docker -v --color
      - name: Run integration tests on Python 2.7
        run: ansible-test integration --docker -v --color --retry-on-error --python 2.7
      - name: Run integration tests on Python 3.7
        run: ansible-test integration --docker -v --color --retry-on-error --python 3.7
